name: Build Zarf Injector

on:
  pull_request:

jobs:
  build-injector:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        
      - name: "Build Rust Binary for x86_64 and arm64"
        run: |
          make setup
          make injector
          make check-size