name: Security audit

on:
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  audit:
    if: github.repository == 'zarf-dev/zarf-injector'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998 # v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
